export const MOTOR_QUOTE = {
  // quote key:
  partner_code: 'partner_code',
  vehicle_make: 'quick_quote_make',
  vehicle_model: 'quick_quote_model',
  reg_yyyy: 'quick_quote_reg_yyyy',
  start_date: 'quick_proposal_start_date',
  end_date: 'quick_proposal_end_date',
  owner_dob: 'quick_quote_owner_dob',
  owner_drv_exp: 'quick_quote_owner_drv_exp',
  owner_ncd: 'quick_quote_owner_ncd',
  owner_no_of_claims: 'quick_quote_owner_no_of_claims',
  owner_claim_amount: 'quick_quote_owner_claim_amount',
  email: 'quick_quote_email',
  mobile: 'quick_quote_mobile',
  promo_code: 'quick_proposal_promo_code',
  hire_purchase: 'quick_proposal_hire_purchase',
  other_hire_purchase: 'quick_proposal_other_hire_purchase',
  engine_number: 'engine_number',
  chassis_number: 'chassis_number',
};

export const MAID_QUOTE = {
  // quote key:
  partner_code: 'partner_code',
  vehicle_make: 'quick_quote_make',
  vehicle_model: 'quick_quote_model',
  reg_yyyy: 'quick_quote_reg_yyyy',
  start_date: 'quick_proposal_start_date',
  end_date: 'quick_proposal_end_date',
  owner_dob: 'quick_quote_owner_dob',
  owner_drv_exp: 'quick_quote_owner_drv_exp',
  owner_ncd: 'quick_quote_owner_ncd',
  owner_no_of_claims: 'quick_quote_owner_no_of_claims',
  owner_claim_amount: 'quick_quote_owner_claim_amount',
  email: 'quick_quote_email',
  mobile: 'quick_quote_mobile',
  promo_code: 'quick_proposal_promo_code',
  hire_purchase: 'quick_proposal_hire_purchase',
  other_hire_purchase: 'quick_proposal_other_hire_purchase',
  maid_type: 'maid_type',
  plan_period: 'plan_period',
  nationality: 'nationality',
  maid_dob: 'date_of_birth',
  name: 'name',
  fin: 'fin',
  passport_number: 'passport_number',
  company_name: 'company_name',
  company_name_other: 'company_name_other',
  has_helper_worked_12_months: 'has_helper_worked_12_months',
};
